### ISSUE TITLE
After Login Error authByRequestPollingID

### ISSUE THREAD

**Issue by Wr4YTh** [Achaak/toogoodtogo-bot#10]
After the login I got this error:

Error authByRequestPollingId
Error: ENOENT: no such file or directory, open './.storage/data.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)

What do I wrong?

**Comment by JMF386** [comment]
Open the console, make a "cd" command to go on the root of the bot.
Then do the following command: mkdir ".storage"

Once this is done, go to this directory and create a file "data.json".

Finally, open this json file to insert the brackets as on the picture.
![image](https://user-images.githubusercontent.com/42487204/159029720-de643329-1bcc-4a49-a124-103ddf121581.png)

You save the file, you (re)start the bot, you proceed to the login and if everything goes well, you should have as message "You are connected."

That's it!

**Comment by Achaak** [comment]
I just applied the fix
Thank you :)
