### ISSUE TITLE
Not working ?

### ISSUE THREAD

**Issue by Saku241** [Achaak/toogoodtogo-bot#2]
Hello
I’ve set everything including telegram bot but I got no notifications. 

I know it works because I got that email from TGTG that says a new device has connected but no notifications...

any ideas ?
Thanks

**Comment by Achaak** [comment]
Hi,
Do you have configurate the bot_token parameter in the file config and set enable parameter to true?
And do you have launch the bot notification with the command /start in Telegram ?

**Comment by Saku241** [comment]
Yes everything is fine because if I put /start in my telegram bot
I got this respond :
« Welcome XXXX !
Don't worry, I'll let you know if there are new stocks. :) »
But if I look in my TGTG account in my favorite business, they are new stocks
