### ISSUE TITLE
Docker container build error

### ISSUE THREAD

**Issue by dennisvanderpool** [Achaak/toogoodtogo-bot#21]
Sending build context to Docker daemon    385kB
Step 1/8 : FROM node:16-alpine
 ---> 0e1140518c5f
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 13425d754208
Step 3/8 : COPY package.json yarn.lock ./
 ---> Using cache
 ---> 696b55c2888c
Step 4/8 : RUN yarn --frozen-lockfile
 ---> Using cache
 ---> b29a22dc8607
Step 5/8 : COPY . .
 ---> Using cache
 ---> 40e143f4e261
Step 6/8 : EXPOSE 3000
 ---> Using cache
 ---> eacf49cf89e1
Step 7/8 : RUN yarn build
 ---> Running in b102571378e0
yarn run v1.22.19
$ tsc
src/core/index.ts(6,20): error TS2307: Cannot find module '../../config/config.js' or its corresponding type declarations.
src/lib/console/index.ts(3,20): error TS2307: Cannot find module '../../../config/config.js' or its corresponding type declarations.
src/lib/dataManager/index.ts(7,20): error TS2307: Cannot find module '../../../config/config.js' or its corresponding type declarations.
src/lib/telegram/index.ts(1,20): error TS2307: Cannot find module '../../../config/config.js' or its corresponding type declarations.
src/services/API/config.ts(2,20): error TS2307: Cannot find module '../../../config/config.js' or its corresponding type declarations.
src/services/API/connect.ts(2,20): error TS2307: Cannot find module '../../../config/config.js' or its corresponding type declarations.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 2

**Comment by Morphclue** [comment]
The problem here is that the `config.js` is missing in the `dist`-folder.
After you've build your project with yarn you can copy your `config.js` manually to `dist/config/config.js`. Note that you might need to create a new folder `config` inside `dist`.
This is only a temporary fix for this problem.

**Comment by dennisvanderpool** [comment]
Thanks, I will give it a try, should have read the README.... Oops 😁

**Comment by simzdk** [comment]
Getting the same error. 

"Error authByEmail"
