### ISSUE TITLE
Error with pm2 start start.sh

### ISSUE THREAD

**Issue by samuelbgn** [Achaak/toogoodtogo-bot#22]
pm2 start start.sh when I try to launch this cmd I've got this error : [PM2][ERROR] Interpreter bash is NOT AVAILABLE in PATH. (type 'which bash' to double check.)
I tried directly npm run start but still not work: 
Error authByEmail
<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={'rt':'c','cid':'AHrlqAAAAAMAOCRdIcP8edIAbaTMIA==','hsh':'1D42C2CA6131C526E09F294FE96F94','t':'fe','r':'b','s':35588,'e':'e12eaa6ed2dc5f2baa5f990f2c5faab1c570d8992d775ebcbf9719855bb6cb7d','host':'geo.captcha-delivery.com'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>

**Comment by dennisvanderpool** [comment]
Hi, I have the same thing. Did you got it resolved yet?
