### ISSUE TITLE
cannot find the config file I need

### ISSUE THREAD

**Issue by maxxol** [Achaak/toogoodtogo-bot#25]
yarn start creates:
Error authByEmail
{
  errors: [ { code: 'VALIDATION_ERROR', message: 'email must not be blank' } ]
}

im guessing i need to put the info in some config file but I have checken every folder and can't find it

**Comment by Achaak** [comment]
You need to put this information in the .env.local file you're about to create.
https://github.com/Achaak/toogoodtogo-bot?tab=readme-ov-file#configure-environment-variables
