### ISSUE TITLE
Suggest : add location

### ISSUE THREAD

**Issue by Saku241** [Achaak/toogoodtogo-bot#3]
Hello
In Telegram alert all it says is something like « Business : # of stock »
But I got same business in different town. Is it possible to add the location like in the TGTG app ?
Something like « Business - Location : # »

thanks !

**Comment by Achaak** [comment]
Hi,
Unfortunately I can't retrieve just the name of the town.
Only the full address is returned but this does not make the notifications unreadable.

**Comment by Saku241** [comment]
oh alright because as you can see in the original app I got a business called « Boulangerie Thirion » and there’s one in two different town. This variable can’t be called with the API?

![B09F1006-6405-4765-BB36-FCA38D8690A3](https://user-images.githubusercontent.com/13026940/104106559-20570a00-52b7-11eb-8128-ddb359688069.jpeg)

**Comment by Achaak** [comment]
The api returns the parameters: city, address, postcode but only the address (which contains street, city, postcode) is returned with a value. The others are always empty.
