### ISSUE TITLE
1.1.0 not working ?

### ISSUE THREAD

**Issue by Saku241** [Achaak/toogoodtogo-bot#5]
Hello

Im still having issues with 1.1.0.

I put telegram notification (it was working fine in 1.0.0), same Token and credentials.
I just edit the user agent to recognize the station. 
I run it : 
```
pi@raspberrypi:~/toogoodtogo-bot $ npm run start

> toogoodtogo-bot@1.1.0 start /home/pi/toogoodtogo-bot
> ts-node ./dist/src/index.js

Your are connected.
```
But I dont receive any notification on telegram now :/ 
(Btw "Your are connected." is misspelled > "You are connected")

**Comment by Achaak** [comment]
Hi do you have send /start in telegram ?

**Comment by Saku241** [comment]
yep, should I run it again ?

**Comment by Achaak** [comment]
I have the impression that by getting the latest version, it has overwritten your settings.
You can try it just in case.
