### ISSUE TITLE
How to insert email and password?

### ISSUE THREAD

**Issue by LauraCardillo** [Achaak/toogoodtogo-bot#6]
Sorry for the stupid question but how I can insert my credentials?

I try to modify the config file but it's a red-only

**Comment by Achaak** [comment]
Hi !
You are in linux, Mac or Windows ?

**Comment by LauraCardillo** [comment]
Now i'm using virtualbox with ubuntu installed but the windows' steps will be useful too

**Comment by Achaak** [comment]
On Linux use this command
```
chmod 777 config.js

Or

sudo chmod 777 config.js
```

On windows it's in parameters (right click)

**Comment by LauraCardillo** [comment]
Thanks dude.
It finally works!
