### ISSUE TITLE
"Your email or password is incorrect."

### ISSUE THREAD

**Issue by atemerino** [Achaak/toogoodtogo-bot#7]
Whenever I try to start the bot, it returns "Your email or password is incorrect."

Oddly enough, logging in on https://store.toogoodtogo.com/login does not work either.
On my phone logging in on the app works just fine.

Is there an issue at the moment with loggin in?

**Comment by bobkelso974** [comment]
Hi, in the "config.default.js" file, I changed this line " User-Agent ":" TooGoodToGo / 21.9.0 (813) "
and it worked for me

**Comment by basti1499** [comment]
@Achaak any news on this issue? :D

**Comment by jozefszymala** [comment]
@Achaak I am also curious is it already fixed?

**Comment by basti1499** [comment]
> @Achaak I am also curious is it already fixed?

I don't think so, the original version works though, you can find it here: https://github.com/marklagendijk/node-toogoodtogo-watcher

TGTG changed the login method from email and pw to email and verification code, it just wasn't updated in this project.

**Comment by Achaak** [comment]
I haven't had time for the past few months, but I'll try to watch it this weekend 😉

**Comment by basti1499** [comment]
> I haven't had time for the past few months, but I'll try to watch it this weekend 😉

Just out of interest, is there a difference between your project and the other one ? 😄

**Comment by Achaak** [comment]
To be honest there is not much difference, I wanted to challenge myself and be able to be master of my project 😄

I just fixed the login problem 🙂
